node {
    def mvnHome
    stage('Preparation') {
        mvnHome = tool 'M3'
        cleanWs()
        checkout scm
        sh "git checkout ${env.GIT_BRANCH}"
        sh "git diff origin/master"
        sh 'git diff origin/master > DiffblueTests.patch'
    }

    stage ('Diffblue-Clean') {
        sh 'mvn clean install -DskipTests'
        sh '/opt/Diffblue/dcover clean'
        sh 'mvn test-compile'
        sh '/opt/Diffblue/dcover clean --failing'
        sh 'mvn test'
        //githubPRComment comment: githubPRMessage('Tests have been cleaned')
    }

    stage('Diffblue-Create') {
        def lastCommit = sh(script: "git rev-list HEAD -1 --no-merges", returnStdout: true)
        def lastNonBotCommit = sh(script: "git rev-list -1 --author='^(?!Diffblue CI).*\$' --perl-regexp HEAD --no-merges", returnStdout: true)
        if (lastCommit == lastNonBotCommit) { 
            sh "git diff origin/master > change.patch"
            sh "/opt/Diffblue/dcover create -p change.patch"
            sh "rm change.patch"
            sh "git add *.java"
            sh "git commit -m \"Update Diffblue Tests\""
            withCredentials([usernamePassword(credentialsId: 'GITHUB-HTTPS', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
                sh "git push https://${GIT_USERNAME}:${encodedPassword}@github.com/ThomasPerkins1123/CoreBanking-JenkinsTest.git"
                def repository_url = scm.userRemoteConfigs[0].url
                def repository_name = repository_url.replace("git@github.com:","").replace(".git","")
                sh "curl -s --location --request POST --header \"Authorization: Bearer ${GIT_PASSWORD}\" --header \"Content-Type: application/json\" https://api.github.com/repos/ThomasPerkins1123/CoreBanking-JenkinsTest/issues/${ghprbPullId}/comments --data \"{\\\"body\\\": \\\"<HEADER><b><u>Diffblue Cover:</u></b> New feature & accidental regression<br><TEST-GEN><b>Test Generation Status:</b> Diffblue has pushed a commit to your PR with the updated unit tests :heavy_check_mark: <i>Please inspect the test diff to determine of the behaviour change is as expected</i>\\\"}\""
            }
        } else {
            withCredentials([usernamePassword(credentialsId: 'GITHUB-HTTPS', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                sh "curl -s --location --request POST --header \"Authorization: Bearer ${GIT_PASSWORD}\" --header \"Content-Type: application/json\" https://api.github.com/repos/ThomasPerkins1123/CoreBanking-JenkinsTest/issues/${ghprbPullId}/comments --data \"{\\\"body\\\": \\\"<HEADER><b><u>Diffblue Cover:</u></b> Update Diffblue Tests<br><TESTS><b>Baseline Tests Status:</b> Existing Tests Pass :heavy_check_mark:<br>\\\"}\""
            }
        }
    }
}

