image: ubuntu:latest

variables:
  BRANCH_PREFIX: "corebanking-demo"

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get --yes --force-yes install wget git maven unzip python3 curl
  - git config --global pull.ff only
  - git remote set-url origin https://$GIT_CI_USER:$GH_DB_TOKEN@gitlab.com/$CI_PROJECT_PATH.git
  - git config --global user.email "db-ci-platform@diffblue.com"
  - git config --global user.name "Diffblue CI"


stages:
  - run_existing_diffblue_tests
  - generate

generate-tests:
  stage: generate
  script:
    - git checkout $CI_COMMIT_BRANCH
    - mvn compile -B

    - mkdir dcover
    - cd dcover
    - echo "$RELEASE_URL"
    - wget -c "$RELEASE_URL" -O dcover.zip -q
    - unzip dcover.zip
    - cd ..

    - dcover/dcover create --batch --exclude io.diffblue.corebanking.ui.menu.ClientsMenu.executeMenuOption

    - NEW_BRANCH="$BRANCH_PREFIX/$(date +'%y%m%d%H%M')"
    - git checkout -b "$NEW_BRANCH"
    - git branch
    - git add src/test/java
    - (if ! git diff --quiet --cached src/test/java; then git commit -m "Generate baseline Diffblue Tests"; git push origin "$NEW_BRANCH"; else echo "Nothing to commit"; fi);
  only:
    - master

run-existing-diffblue-tests:
  stage: run_existing_diffblue_tests
  script:
    - mvn test -B
  only:
    - merge_requests
  allow_failure: true

update-diffblue-tests:
  stage: generate
  script:
    - git fetch origin
    - git checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - ./updateTests.sh $RELEASE_URL $GH_DB_TOKEN $CI_PROJECT_ID $CI_MERGE_REQUEST_IID
  only:
    - merge_requests
