name: corebanking-pr

trigger: none
pr:
  branches:
    include:
    - corebanking-demo/*

variables:
- name: COMMENT_ID
  value: "<b><u>Diffblue Cover:</u></b> $(git show -s --format=%s)" # An ID user for the script that add a comment to the PRs
- name: COMMENT_SCRIPT_LOCATION
  value: "$(realpath azure-pipelines/scripts/addComment.py)" # A path to the example script for commenting on PRs

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: run_diffblue_tests
  displayName: Run Diffblue Tests
  steps:
  - checkout: self
    persistCredentials: true

  - script: |
      git checkout "$(System.PullRequest.SourceBranch)"
    displayName: 'Checkout Branch'

  - script: |
      git config --global pull.ff only
      git config --global user.email "db-ci-platform@diffblue.com" # Configure git user to be a Diffblue Bot (When making commits, this does not affect comments)
      git config --global user.name "Diffblue CI"
    displayName: 'Config git user'

  - script: |
      python3 $(COMMENT_SCRIPT_LOCATION) \ # An example script that will comment on a PR
      --token $(GH_DB_TOKEN) \
      --pr_number $(System.PullRequest.PullRequestNumber) \
      --comment_id "$(COMMENT_ID)" \
      --line_tag "<TESTS>" \
      --message "<b>Baseline Tests Status:</b> Running Tests :hourglass_flowing_sand:"
    displayName: 'Comment on PR (Tests started)'

  - script: |
      mvn clean test -B # Replace this with a command to run Diffblue tests only on your project
    displayName: 'Run tests'

  - script: |
      python3 $(COMMENT_SCRIPT_LOCATION) \
      --token $(GH_DB_TOKEN) \
      --pr_number $(System.PullRequest.PullRequestNumber) \
      --comment_id "$(COMMENT_ID)" \
      --line_tag "<TESTS>" \
      --message "<b>Baseline Tests Status:</b> Existing Tests Pass :heavy_check_mark:" 
    displayName: 'Comment on PR (Tests Pass)'
    condition: succeeded()

  - script: |
      python3 $(COMMENT_SCRIPT_LOCATION) \
      --token $(GH_DB_TOKEN) \
      --pr_number $(System.PullRequest.PullRequestNumber) \
      --comment_id "$(COMMENT_ID)" \
      --line_tag "<TESTS>" \
      --message "<b>Baseline Tests Status:</b> Existing Tests Fail :x:"
    displayName: 'Comment on PR (Tests Fail)'
    condition: failed()

- job: update_diffblue_tests
  displayName: Update Diffblue Tests
  dependsOn: run_diffblue_tests
  condition: or(succeeded(), failed())
  variables:
  - name: last_bot_commit

  steps:
  - checkout: self
    persistCredentials: true
  
  - script: |
      git checkout "$(System.PullRequest.SourceBranch)"
    displayName: 'Checkout Branch'

  - script: |
      git config --global pull.ff only
      git config --global user.email "db-ci-platform@diffblue.com"
      git config --global user.name "Diffblue CI"
    displayName: 'Config git user'

  - script: |
      LAST_NON_BOT_COMMIT="$(git rev-list -1 --author='^(?!Diffblue CI).*$' --perl-regexp HEAD --no-merges)" # Checks if the last commit can from the bot (If we do not check this and there is some non-determinism in dcover then this creates an infinite CI loop)
      echo "Last non bot commit is $LAST_NON_BOT_COMMIT"
      LAST_COMMIT="$(git rev-list HEAD -1 --no-merges)"
      echo "Last commit is $LAST_COMMIT"
      if [[ "$LAST_NON_BOT_COMMIT" == "$LAST_COMMIT" ]]
      then
        echo "##vso[task.setvariable variable=last_bot_commit]0"
      else
        echo "##vso[task.setvariable variable=last_bot_commit]1"
      fi
    displayName: 'Check if last commit was bot commit'

  - script: |
      python3 $(COMMENT_SCRIPT_LOCATION) \
      --token $(GH_DB_TOKEN) \
      --pr_number $(System.PullRequest.PullRequestNumber) \
      --comment_id "$(COMMENT_ID)" \
      --line_tag "<TEST-GEN>" \
      --message "<b>Test Generation Status:</b> Diffblue Cover is generating tests for this pull request :hourglass_flowing_sand:"
    displayName: 'Comment on PR (First run)'
    condition: eq(variables.last_bot_commit, 0)

  - script: |
      mvn compile -B # Replace with the commands needed to buiold your project
    displayName: 'Build CoreBanking'
    condition: eq(variables.last_bot_commit, 0)

  - script: |
      mkdir dcover
      cd dcover
      wget -c "$(RELEASE_URL)" -O dcover.zip -q # Download Dcover from a secure URL
      unzip dcover.zip
    displayName: 'Get Dcover'
    condition: eq(variables.last_bot_commit, 0)

  - script: |
      git diff origin/"$(System.PullRequest.TargetBranch)" > DiffblueTests.patch # Create a patch fie for all chnages in this PR
      PATCH_FILE=$(realpath DiffblueTests.patch)
      dcover/dcover create --batch --patch-only $PATCH_FILE --exclude io.diffblue.corebanking.ui.menu.ClientsMenu.executeMenuOption # Use the patch file to only regenerate tests for code that has changed or code that is dependant on code that has changed
    displayName: 'Generate tests'
    condition: eq(variables.last_bot_commit, 0)

  - script: |
      git add src/test/java
      if ! git diff --quiet --cached src/test/java
      then
        python3 $(COMMENT_SCRIPT_LOCATION) \
          --token $(GH_DB_TOKEN) \
          --pr_number $(System.PullRequest.PullRequestNumber) \
          --comment_id "$(COMMENT_ID)" \
          --line_tag "<TEST-GEN>" \
          --message "<b>Test Generation Status:</b> Diffblue has pushed a commit to your PR with the updated unit tests :heavy_check_mark: <i>Please inspect the test diff to determine of the behaviour change is as expected</i>"

        git commit -m "Update Diffblue Tests"
        git push
      else
        python3 $(COMMENT_SCRIPT_LOCATION) \
          --token $(GH_DB_TOKEN) \
          --pr_number $(System.PullRequest.PullRequestNumber) \
          --comment_id "$(COMMENT_ID)" \
          --line_tag "<TEST-GEN>" \
          --message "<b>Test Generation Status:</b> Diffblue has finished analysing your pull request but deteced no changes :heavy_check_mark:"

        echo "Nothing to commit"
      fi
    displayName: 'Commit Changes'
    condition: eq(variables.last_bot_commit, 0)

