name: corebanking-start

trigger:
- main
pr: none

variables:
- name: BRANCH_PREFIX
  value: corebanking-demo 

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git checkout "$(Build.SourceBranchName)"
  displayName: 'Checkout Branch'

- script: |
    git config --global pull.ff only
    git config --global user.email "db-ci-platform@diffblue.com"
    git config --global user.name "Diffblue CI"
  displayName: 'Config git user'

- script: |
    mvn compile -B
  displayName: 'Build CoreBanking'

- script: |
    mkdir dcover
    cd dcover
    wget -c "$(RELEASE_URL)" -O dcover.zip -q
    unzip dcover.zip
  displayName: 'Get Dcover'

- script: |
    dcover/dcover create --batch --exclude io.diffblue.corebanking.ui.menu.ClientsMenu.executeMenuOption
  displayName: 'Generate tests'

- script: |
    NEW_BRANCH="$(BRANCH_PREFIX)/$(date +'%y%m%d%H%M')"
    git fetch origin
    git checkout -b "$NEW_BRANCH"
    git branch
    git add src/test/java
    if ! git diff --quiet --cached src/test/java
    then
      git commit -m "Generate baseline Diffblue Tests"
      git push origin "$NEW_BRANCH"
    else
      echo "Nothing to commit"
    fi
  displayName: 'Push Changes'

