name: corebanking-start

trigger:
- main
pr: none

variables:
- name: BRANCH_PREFIX
  value: corebanking-demo # Branch prefix used for all baseline test branches

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git checkout "$(Build.SourceBranchName)"
  displayName: 'Checkout Branch'

- script: |
    git config --global pull.ff only
    git config --global user.email "db-ci-platform@diffblue.com" # Configure git user to be a Diffblue Bot
    git config --global user.name "Diffblue CI"
  displayName: 'Config git user'

- script: |
    mvn compile -B # Replace with whatever build commands are needed for your project
  displayName: 'Build CoreBanking'

- script: |
    mkdir dcover
    cd dcover
    wget -c "$(RELEASE_URL)" -O dcover.zip -q # Download Dcover from a secure URL
    unzip dcover.zip
  displayName: 'Get Dcover'

- script: |
    dcover/dcover create --batch --exclude io.diffblue.corebanking.ui.menu.ClientsMenu.executeMenuOption # Create tests for all classes using batch mode to improve the output in log files
  displayName: 'Generate tests'

- script: |
    NEW_BRANCH="$(BRANCH_PREFIX)/$(date +'%y%m%d%H%M')"
    git fetch origin
    git checkout -b "$NEW_BRANCH" # create a new baseline branch based on the date and time
    git branch
    git add src/test/java
    if ! git diff --quiet --cached src/test/java # Check that the tests have actually changed
    then
      git commit -m "Generate baseline Diffblue Tests"
      git push origin "$NEW_BRANCH"
    else
      echo "Nothing to commit"
    fi
  displayName: 'Push Changes'

